### ISSUE TITLE
Add minitest and rspec matchers

### ISSUE THREAD

**Issue by tobidelius** [jsonapi-rb/jsonapi-rb#2]
Really awesome project, good work!

Perhaps a new sub repo could include helper methods for testing with Minitest and RSpec or is that out of the scope for the project?

**Comment by beauby** [comment]
Hi @sandelius, thanks for your kind words! That's definitely something I'd be interested in, but do not have the necessary bandwidth for at the moment. In the meantime you could use @richmolj [spec helpers](https://jsonapi-suite.github.io/jsonapi_suite/#spec-helpers) from his [jsonapi_suite gem](https://jsonapi-suite.github.io/jsonapi_suite).

**Comment by beauby** [comment]
FYI https://github.com/jsonapi-rb/jsonapi-rspec

**Comment by tobidelius** [comment]
@beauby wonderful! I'm closing this now :)
