### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by caseyprovost** [jsonapi-rb/jsonapi-rb#5]
Just wondering if this has been abandoned or not. Not seeing a commit in about 2 years and there is still a fair bit of documentation missing.

**Comment by WaKeMaTTa** [comment]
I would say it still alive. This gem is a wrapper that is why it doesn't change a lot.

**Comment by beauby** [comment]
As @WaKeMaTTa mentioned, this gem simply bundles other gems, _as is written on the [README](https://github.com/jsonapi-rb/jsonapi-rb#code)_. Note also that it is free software and that you are welcome to help building stronger docs.
