### ISSUE TITLE
Error handling with alias

### ISSUE THREAD

**Issue by bsylvain** [jsonapi-rb/jsonapi-rb#6]
Is there a way to make the errors pointer match the alias used in the serializer ?

serializer : 
```
     attribute :reply do
        @object.content
    end
```
response when there is an error : 
`{"errors":[{"title":"Invalid content","detail":"Nouveau commentaire est trop court (au moins 16 caractères)","source":{}}],"jsonapi":{"version":"1.0"}}`

Idealy source should contain a pointer to reply.
How can the errors be correctly serialized ?

**Comment by beauby** [comment]
Would you mind moving this issue to either [jsonapi-rails](https://github.com/jsonapi-rb/jsonapi-rails) (if using `jsonapi-rails`), or [jsonapi-serializable](https://github.com/jsonapi-rb/jsonapi-serializable) otherwise?
